# See: https://github.com/marketplace/actions/release-drafter

name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "Features"
    labels:
      - "checker"
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Maintenance"
    labels:
      - "chore"
      - "clean"
      - "cleanup"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## Changes

  $CHANGES
